# Generated by Django 4.1.7 on 2023-03-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_added',
            field=models.DateField(auto_created=True, default=2014),
            preserve_default=False,
        ),
    ]
